### ISSUE TITLE
Enable PHP 7 tests on Travis CI

### ISSUE THREAD

**Issue by sergeyklay** [aerospike-community/aerospike-client-php5#127]
I spent two days to figure out how to run tests on Travis CI. I'm interested in the possibility of testing different PHP versions. For example:
```yaml
language: php

php:
  - 5.5
  - 5.6
  - 7.0
```

So could you please add to the current `.travis.yml` some configuration to show an approach how to do the things described above?

Thanks
